### ISSUE TITLE
Generic Viewer Implementation in Portal-UI

### ISSUE THREAD

**Issue by kohsah** [gawati/gawati-portal-ui#96]
Provision viewers for different file formats based on the style used in the DocumentPDF viewer. 

As per the file format - the appropriate viewer implementation must be loaded. 

This allows the possibility of adding custom viewers for formats that are unknown to us.

**Comment by nilamshirke** [comment]
Some of the conversion requires a back-end api since the conversion cannot be done purely in the front-end.  For example, for rendering DOCX the following would apply -- 

1. Create API to convert docx file to HTML (for rendering purposes) on gawati-portal-fe 
  * input for api: document IRI
  * output from api: html
2. DocumentDOCX component in React to be implemented in portal-ui which calls the API and presents the   HTML .

**Comment by kohsah** [comment]
This needs to be rewritten and factored into a generic component (with frontend react components and back-end implementation )  so it can be used in both editor ui and portal ui. See https://github.com/gawati/gawati-editor-ui/issues/40

**Comment by kohsah** [comment]
This issue has been fixed
